export type BottlePromptPack = 'off' | 'party' | 'flirty';

/** Friendly truths and dares for a mixed group. Never explicit. */
export const PARTY_PROMPTS: string[] = [
  'Do your best impression of someone else in the room.',
  "Sing the chorus of your favorite song, even if you can't sing.",
  'Tell everyone your most embarrassing childhood nickname.',
  'Let the group pick an emoji to describe you.',
  'Do 10 jumping jacks right now.',
  'Speak in an accent for the next two rounds.',
  "Show the group your camera roll's last photo.",
  "What's the last lie you told, and why?",
  "Text a friend 'I just won a llama' and show the reply.",
  'Do your best dance move for 10 seconds.',
  "What's the weirdest food combination you actually enjoy?",
  "Let someone else post anything they want on your phone's notes app.",
  'Balance something on your head for the next minute.',
  "What's a talent nobody here knows you have?",
  "Try to lick your elbow.",
  "Tell a joke. If nobody laughs, take a sip of your drink.",
  'What was your first impression of the person to your left?',
  'Do an impression of a celebrity until someone guesses who it is.',
  "What's the most trouble you ever got into at school?",
  'Let the group choose your profile picture for a week.',
  'Swap seats with someone for the next round.',
  "What's your go-to karaoke song?",
  'Do a cartwheel or your best attempt at one.',
  "Tell the group about a time you embarrassed yourself in public.",
  'Speak only in questions for the next two minutes.',
  "What's the strangest thing in your bag or pockets right now?",
  'Give a one-minute stand-up comedy bit about anything.',
  "What's a rumor you've heard about yourself?",
  'Do your best robot dance.',
  "Describe your perfect weekend in exactly five words.",
  'Let someone draw a tiny doodle on your hand.',
  "What's the last thing you searched on your phone?",
  'Act out your morning routine without speaking.',
  "What's a skill you wish you had?",
  'Try to make the group laugh without saying a word.',
  "What's your most-used emoji?",
  'Hum a song and have the group guess it.',
  "What's the last show you binge-watched?",
  'Do your best impression of a news anchor for 20 seconds.',
  "What's a food you refuse to eat?",
  'Walk like a runway model across the room.',
  "What's the most spontaneous thing you've ever done?",
  'Let the group pick your next social media caption.',
  "What's your favorite childhood memory?",
  'Do your best animal impression.',
  "What's a habit you're trying to break?",
  'Recite the alphabet backwards as fast as you can.',
  "What's the best gift you've ever received?",
  'Give a fake weather report for tomorrow, dramatically.',
  "What's a movie you can quote from memory?",
  'Do an interpretive dance about your day.',
  "What's your go-to comfort food?",
  'Try to whistle a full verse of any song.',
  "What's the last thing that made you laugh really hard?",
  'Say the most tongue-twisting sentence you can think of, three times fast.',
  "What's a trend you never understood?",
  'Give your best toast to the group, on the spot.',
  "What's your dream job, and why?",
  'Do your best superhero pose and name your power.',
  "What's the silliest fear you have?",
  'Let the group rename your phone contact as anything for a day.',
];

/** Playful, flirty prompts. Suggestive, never explicit, for confirmed 18+ groups only. */
export const FLIRTY_PROMPTS: string[] = [
  'Whisper something sweet in the ear of the person to your right.',
  'Give someone here a slow, lingering hug.',
  "Tell the group who here you'd want to be stranded on an island with.",
  'Hold hands with the person across from you for one full minute.',
  "What's the most attractive quality in a partner, to you?",
  'Give a playful wink to everyone at the table, one by one.',
  'Trade a piece of clothing with someone for the rest of the round.',
  "Describe your ideal first date in detail.",
  'Sit on the lap of the person to your left for one round.',
  "What's a compliment you wish people gave you more often?",
  'Give the group your best flirty pickup line.',
  "Tell the person to your right one thing you find attractive about them.",
  'Feed a snack to the person across from you.',
  "What's the most romantic thing anyone has done for you?",
  'Slow dance with someone for 15 seconds, even without music.',
  "Describe your celebrity crush without naming them, let the group guess.",
  'Give someone a lingering look across the room for 10 seconds.',
  "What's your idea of the perfect kiss?",
  'Let someone here choose a playful nickname for you for the night.',
  "Share the story of your first crush.",
  'Give a gentle shoulder massage to the person next to you.',
  "What's a physical feature you notice first in someone?",
  'Trade seats so you sit next to your choice for the rest of the game.',
  "Tell the group your most memorable date, without naming names.",
  'Hold eye contact with someone for 20 seconds without laughing.',
  "What's the boldest move you've made on someone you liked?",
  'Let someone braid or mess up your hair playfully.',
  "Describe your type in exactly three words.",
  'Give a playful compliment to everyone in the circle.',
  "What song instantly puts you in a romantic mood?",
  'Trace a heart on the palm of the person next to you.',
  "Admit the last time you got butterflies, and for whom.",
  'Let the group vote on who you have the best chemistry with here.',
  "What's a small gesture that means a lot to you romantically?",
  'Give a playful nickname to your neighbor and use it for the round.',
  "Share the cheesiest pickup line you've ever heard.",
  'Rest your head on someone’s shoulder for one full minute.',
  "What's your favorite way to be complimented?",
  'Give a slow high-five that turns into holding hands for a moment.',
  "Describe the last time you felt really wanted.",
  'Let someone whisper a secret compliment in your ear.',
  "What's the most charming thing a stranger has ever said to you?",
  'Share your most romantic what-if fantasy, keeping it PG.',
  'Offer a warm hand-hold to whoever is on your left.',
  "What outfit makes you feel most confident and attractive?",
  'Give your best sultry look to the camera for a group photo.',
  "Tell the group about your idea of a perfect slow dance.",
  'Let someone draw a little heart on your hand with their finger.',
  "What's a compliment that made you blush recently?",
  'Share a flirty text you once sent (or wish you had).',
  "Describe your dream romantic getaway in one sentence.",
  'Give a playful shoulder bump to your crush in the room, real or joking.',
  "What's your favorite scent on a partner?",
  'Let the group decide who gives you a compliment next.',
  "Share the most romantic movie scene you can think of.",
  'Hold the hand of the person across from you and maintain eye contact for 10 seconds.',
  "What's one thing you find irresistibly charming?",
  'Give a warm, lingering hug to whoever asks first.',
  "Describe your perfect Sunday morning with someone special.",
  'Whisper your favorite compliment to receive into the ear of your neighbor.',
  "Admit who in the room has the best smile, and why.",
];

export function promptPool(pack: BottlePromptPack): string[] {
  if (pack === 'party') return PARTY_PROMPTS;
  if (pack === 'flirty') return FLIRTY_PROMPTS;
  return [];
}
