import type { CouplesKind, CouplesLevel } from '../../types';

export type { CouplesKind, CouplesLevel };

export const COUPLES_LEVELS: readonly CouplesLevel[] = ['sweet', 'flirty', 'spicy'];
export const COUPLES_LEVEL_RANK: Record<CouplesLevel, number> = { sweet: 0, flirty: 1, spicy: 2 };

/** The lower of two chosen levels, so a session never plays above what either partner picked. */
export function lowerLevel(a: CouplesLevel, b: CouplesLevel): CouplesLevel {
  return COUPLES_LEVEL_RANK[a] <= COUPLES_LEVEL_RANK[b] ? a : b;
}

/** A dare phrased "...for N seconds/minutes" gets an on-screen countdown for that long. */
export function timerSecondsFor(text: string): number | null {
  const seconds = text.match(/for (\d+) seconds?/i);
  if (seconds) return Number(seconds[1]);
  const minutes = text.match(/for a?n? ?(\d+)[- ]minute/i);
  if (minutes) return Number(minutes[1]) * 60;
  return null;
}

const SWEET_TRUTHS = [
  "What's a small thing I do that makes your day better?",
  'When did you first realize you had feelings for me?',
  "What's your favorite memory of us so far?",
  'What made you smile about me today?',
  "What's one thing you're grateful for in our relationship?",
  'What song reminds you of us?',
  "What's the kindest thing I've ever done for you?",
  'What do you look forward to most about our future together?',
  "What's a habit of mine you secretly love?",
  'When do you feel most loved by me?',
  "What's your favorite way to spend a lazy day with me?",
  'What did you think of me the very first time we met?',
  "What's something you admire about how I treat other people?",
  'What made you decide I was worth taking a chance on?',
  "What's a tiny moment with me you still think about?",
  'What do you love most about how we communicate?',
  "What's the silliest thing we've laughed about together?",
  'What comfort food reminds you of a good day with me?',
  "What's one dream you'd love for us to chase together?",
  'When did you feel closest to me this past month?',
  "What's a compliment you've wanted to give me but haven't said out loud?",
  "What's your favorite thing about our home together?",
  'What tradition do you want us to start?',
  "What's something I do without thinking that means a lot to you?",
  'What place do you want us to visit together someday?',
  "What's a story about us you'd want to tell our grandkids?",
  'What do you think makes our relationship different from others?',
  "What's the most peaceful you've felt with me?",
  'What made you fall a little more for me recently?',
  "What's a quality of mine you hope never changes?",
  'What do you love about the way I laugh?',
  "What's something small I could do this week that would mean the world to you?",
  'What was going through your mind on our first date?',
  "What's your favorite nickname for me, and why?",
  'What do you think our friends would say makes us a good match?',
  "What's a lesson you've learned from being with me?",
  'What do you love most about lazy mornings together?',
  "What's the sweetest thing you remember me saying?",
  'What do you hope we never stop doing together?',
  "What's something about me that surprised you in a good way?",
];

const SWEET_DARES = [
  'Hold my hands and tell me three things you love about me.',
  'Give me a hug that lasts for 30 seconds.',
  'Write me a one-sentence love note right now.',
  'Slow dance with me for one song, even without music.',
  'Give me your best impression of how I looked the day we met.',
  "Tell me a story about 'us' like it's a fairy tale.",
  'Give me a forehead kiss and tell me why you picked that moment.',
  'Draw a small heart on my hand and sign it.',
  'Whisper your favorite memory of us in my ear.',
  'Give me a two-minute shoulder rub.',
  'Recreate our first hug.',
  'Tell me my three best qualities without pausing to think.',
  'Hum our song and let me guess it.',
  'Hold eye contact with me for 30 seconds without laughing.',
  'Give me a compliment in a funny accent.',
  "Write 'I love you because...' and fill in the blank out loud.",
  'Give me a piggyback ride around the room, or try your best.',
  'Feed me a bite of something sweet.',
  'Tell me the story of how you knew you wanted to date me.',
  "Give me your best 'movie kiss' pose, just the pose.",
  'Read me a compliment as if you were a game show host.',
  'Give me a long, warm hug with no talking for a full minute.',
  'Tell me one thing you want us to do together this month.',
  'Trace my initials on my back and have me guess them.',
  'Give me a playlist name that describes our relationship.',
  'Tell me your favorite thing about my voice.',
  "Give me a 'cheers' toast to us with any drink nearby.",
  "Hold my face gently and tell me I'm loved.",
  'Give me a slow, warm hand-hold for one full minute.',
  'Tell me the plot of our love story like a movie trailer voice.',
  'Give me a genuine compliment about something not physical.',
  'Write a two-line poem about me on the spot.',
  'Give me a gentle hair-tousle and a smile.',
  "Tell me what you'd want our song to be if we didn't have one.",
  "Give me a 'cheek to cheek' photo pose together.",
  'Tell me a wish you have for our next year together.',
  'Give me your warmest smile and hold it for 10 seconds.',
  "Whisper one thing you're excited about for our future.",
  "Give me a slow hug goodbye, like we won't see each other for a while.",
  "Tell me what home feels like when I'm around.",
];

const FLIRTY_TRUTHS = [
  'What was the first thing you noticed about me physically?',
  'What outfit of mine do you find most attractive?',
  "What's something I do that you find irresistibly cute?",
  'When did you first want to kiss me?',
  "What's a compliment you love hearing from me?",
  'What was your first impression when we started flirting?',
  "What's a look I give you that you love?",
  'What do you find most charming about the way I flirt?',
  "What's the boldest thing you've thought about doing with me?",
  'What playlist would you make for a date night with me?',
  "What's your favorite way for me to get your attention?",
  'What did you daydream about after our first date?',
  "What's a compliment you've been too shy to say?",
  'What do you find most magnetic about my personality?',
  "What's the most playful memory you have of us flirting?",
  'What do you think about right before you see me?',
  "What's your idea of the perfect flirty text from me?",
  'What small gesture from me makes your heart race?',
  "What's a moment you wished lasted longer between us?",
  'What do you find most attractive about my sense of humor?',
  "What's the first thing you'd want to do if we had a whole night alone?",
  'What outfit would you love to see me in for our next date?',
  "What's a compliment about my body you've been wanting to give?",
  'When did you realize our chemistry was undeniable?',
  "What's your favorite way I show affection in public?",
  "What do you think about when you can't sleep and I'm on your mind?",
  "What's the most flirtatious thing I've ever said to you?",
  'What do you love most about how I look at you?',
  "What's a nickname you'd love for me to call you in private?",
  'What was the moment you knew you were falling for me physically too?',
  "What's your favorite scent on me?",
  'What do you think is our most attractive quality as a couple?',
  "What's something flirty you've wanted to try but haven't asked for?",
  'What was the most tension-filled moment between us?',
  "What's your favorite type of touch from me?",
  'What do you think about my smile?',
  "What's the boldest compliment you've ever given me?",
  'What do you love about how I tease you?',
  "What's a memory of us that still makes you blush?",
  'What would you want to whisper to me right now?',
];

const FLIRTY_DARES = [
  'Whisper something flirty in my ear.',
  'Give me a slow wink from across the room.',
  'Trade a piece of clothing with me for the rest of the round.',
  'Give me a lingering hug that lasts a little too long.',
  'Bite your lip and hold eye contact with me for 10 seconds.',
  'Give me your best sultry look for the camera.',
  'Trace a line down my arm and tell me what you are thinking.',
  'Give me a slow dance, close and unhurried.',
  'Whisper the last thing you daydreamed about me.',
  'Give me a kiss on the neck.',
  'Give me a playful spank on the arm and a wink.',
  'Sit on my lap for the next round.',
  "Give me a long, slow hand-hold and don't let go until told.",
  "Trace my collarbone gently and tell me it's soft.",
  'Give me a compliment while looking me up and down.',
  "Whisper what you'd do if we were alone right now.",
  'Give me a kiss anywhere I choose.',
  'Give me a slow, playful once-over and tell me what you see.',
  'Give me a lingering kiss on the cheek, closer to the lips than usual.',
  'Tug me closer by the hand and hold me there for a moment.',
  'Give me a flirty compliment in a low, slow voice.',
  'Give me a soft bite on the shoulder.',
  'Trace a heart on my chest with your finger.',
  'Give me a slow, teasing tickle on my side.',
  'Give me a kiss that lasts for 10 seconds.',
  'Whisper my name like you mean it.',
  'Give me a playful chase around the room for a kiss.',
  'Give me a lap dance move, just one, however silly.',
  'Give me a slow forehead-to-forehead moment and hold it.',
  'Trace your finger along my jawline.',
  'Give me a compliment about my body, slowly and deliberately.',
  'Give me a kiss and pull away slower than usual.',
  'Give me a playful growl and a grin.',
  'Give me a hand on my waist and pull me in.',
  'Give me a slow, teasing brush of your hand against mine.',
  'Give me a kiss on the inside of my wrist.',
  "Whisper the first thing you'd do if we had the house to ourselves.",
  'Give me a long, appreciative look and describe it out loud.',
  'Give me a slow kiss on the shoulder.',
  'Give me a flirty text as if we just met at a party.',
];

const SPICY_TRUTHS = [
  "What's something you've wanted to try with me but never said?",
  "What's your favorite thing about our physical chemistry?",
  'What outfit of mine drives you wild?',
  "What's a fantasy you've had about us?",
  'What part of my body do you find most attractive?',
  "What's the most exciting moment we've shared in the bedroom?",
  'What turns you on the most about how I touch you?',
  "What's something new you'd like us to explore together?",
  "What was the most spontaneous moment we've had together?",
  "What's a compliment about my body you've never said out loud?",
  'What do you think about when you miss me physically?',
  "What's a place we haven't been intimate that you're curious about?",
  'What do you love most about how our bodies fit together?',
  "What's a memory that still gets you excited?",
  'What would you want us to try on our next anniversary?',
  "What's the most daring thing you've thought about doing with me?",
  'What do you find most seductive about the way I move?',
  "What's a way I could surprise you tonight?",
  "What do you love about our chemistry that words can't fully capture?",
  "What's something you'd want me to whisper to you?",
  'What outfit would you want me to wear just for you?',
  "What's your favorite way to be touched?",
  'What is the most sensual thing about our relationship?',
  "What's a slow, quiet moment between us that turned into something more?",
  "What do you crave most when we're finally alone?",
  "What's a compliment about my touch you've never said?",
  'What was the moment our chemistry felt undeniable?',
  "What's something you find irresistible when we're close?",
  "What do you think about doing differently the next time we're intimate?",
  "What's a way you'd want to be surprised tonight?",
  'What do you love most about how I make you feel wanted?',
  "What's the most vulnerable you've felt being close to me?",
  'What do you think makes our intimacy special?',
  "What's a slow build-up you love before we get close?",
  'What do you love most about how we take our time together?',
  "What's something about tonight you're hoping for?",
  'What do you find most attractive about my confidence?',
  "What's a way I could set the mood for us?",
  'What do you love about how we read each other without words?',
  "What's something you've wanted to whisper to me all day?",
];

const SPICY_DARES = [
  'Kiss me somewhere I choose.',
  'Give me a slow two-minute massage.',
  'Trace your fingers slowly down my back for 30 seconds.',
  'Give me a slow, lingering kiss for 20 seconds.',
  'Whisper exactly what you want to do to me next.',
  'Give me a slow striptease of one item of clothing.',
  'Give me a massage on my neck and shoulders for a full minute.',
  'Trace a slow path with your lips from my ear to my collarbone.',
  'Give me a kiss that starts slow and builds for 15 seconds.',
  'Undress me one button or zipper at a time, slowly.',
  'Give me a lap dance for 30 seconds.',
  'Whisper the next thing you plan to do once the game ends.',
  'Give me a slow, deep kiss with your hands on my face.',
  'Trace a line with your tongue from my collarbone to my ear.',
  'Give me a massage that moves lower with each stroke.',
  'Give me a slow bite on my earlobe.',
  'Give me a long, breathless kiss for 20 seconds.',
  'Trace your fingers along my inner thigh for 15 seconds.',
  'Give me a slow, teasing dance meant just for me.',
  'Whisper what you love most about our bodies together.',
  'Give me a kiss on every part of my face except my lips, then finally my lips.',
  'Give me a slow massage of my hands and wrists.',
  'Trace a slow spiral on my chest with your finger.',
  'Give me a hungry kiss that lasts for 15 seconds.',
  'Give me a slow, seductive walk across the room toward me.',
  'Give me a massage focused entirely on my lower back for a minute.',
  'Whisper a fantasy you want to act out tonight.',
  'Give me a kiss that trails from my lips down to my collarbone.',
  'Give me a slow removal of my socks, one at a time, teasingly.',
  'Give me a deep, slow kiss while holding my waist.',
  'Trace your fingers along my spine for 30 seconds.',
  'Give me a massage of my scalp and neck for a full minute.',
  'Give me a slow, sensual dance for one full song.',
  'Whisper exactly how you want the rest of the night to go.',
  'Give me a kiss that lingers on my neck for 15 seconds.',
  'Give me a slow trace of your hand from my knee to my hip.',
  "Give me a kiss and a promise for later, whispered slowly.",
  'Give me a massage that ends with a kiss wherever you like.',
  'Give me a slow, teasing tug at my waistband and a grin.',
  "Whisper the one thing you can't wait to do once we're alone.",
];

export const COUPLES_DECKS: Record<CouplesLevel, Record<CouplesKind, string[]>> = {
  sweet: { truth: SWEET_TRUTHS, dare: SWEET_DARES },
  flirty: { truth: FLIRTY_TRUTHS, dare: FLIRTY_DARES },
  spicy: { truth: SPICY_TRUTHS, dare: SPICY_DARES },
};

export function couplesPool(level: CouplesLevel, kind: CouplesKind): readonly string[] {
  return COUPLES_DECKS[level][kind];
}

/** Draws one card from `pool`, never repeating until every card has been seen, then reshuffles. */
export function drawFromPool(
  pool: readonly string[],
  used: readonly string[],
  randomIndex: (n: number) => number,
): { text: string; used: string[] } {
  let remaining = pool.filter((p) => !used.includes(p));
  let base = used;
  if (remaining.length === 0) {
    base = [];
    remaining = [...pool];
  }
  const text = remaining[randomIndex(remaining.length)];
  return { text, used: [...base, text] };
}
